Update postprocess.py
I was getting following error because 'mode' variable was referenced before assignment when there was already a directory to save result files.

  File "C:\Users\PC\Documents\GitHub\calvin\calvin\postprocessor.py", line 166, in postprocess
    save_dict_as_csv(data, resultdir + '/' + name + '.csv', mode)

UnboundLocalError: local variable 'mode' referenced before assignment